-- Facilitator: Load the PLAYER_INTELLIGENCE backup CSV
-- 1. Upload player_intelligence_backup.csv to the BACKUP_STAGE via Snowsight UI:
--    Data > Databases > POSTCODE_LOTERIJ_AI > ANALYTICS > Stages > BACKUP_STAGE > + Files
-- 2. Then run this script.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE LOTERIJ_WH;

CREATE STAGE IF NOT EXISTS POSTCODE_LOTERIJ_AI.ANALYTICS.BACKUP_STAGE;

CREATE OR REPLACE TABLE POSTCODE_LOTERIJ_AI.ANALYTICS.PLAYER_INTELLIGENCE AS
SELECT
  $1::NUMBER AS PLAYER_ID, $2::VARCHAR AS PLAYER_CODE, $3::VARCHAR AS PLAYER_NAME,
  $4::VARCHAR AS POSTCODE, $5::VARCHAR AS CITY, $6::DATE AS SUBSCRIPTION_START,
  $7::VARCHAR AS TICKET_TYPE, $8::NUMBER AS MONTHLY_SPEND, $9::VARCHAR AS ACQUISITION_CHANNEL,
  $10::VARCHAR AS STATUS, $11::VARCHAR AS AGE_GROUP, $12::NUMBER AS TENURE_MONTHS,
  $13::VARCHAR AS FEEDBACK_TEXT, $14::FLOAT AS FEEDBACK_SENTIMENT,
  PARSE_JSON($15) AS PLAYER_SEGMENT_JSON, PARSE_JSON($16) AS EXTRACTED_INSIGHTS_JSON,
  $17::NUMBER AS ESTIMATED_LIFETIME_VALUE, $18::FLOAT AS CHARITY_CONTRIBUTION
FROM @POSTCODE_LOTERIJ_AI.ANALYTICS.BACKUP_STAGE/player_intelligence_backup.csv
  (FILE_FORMAT => (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1));
